### ISSUE TITLE
A project file (tsconfig.json or tsconfig.eslint.json) is required in order to use ts-standard.

### ISSUE THREAD

**Issue by manticorp** [sambauers/SublimeLinter-contrib-ts-standard#3]
Whenever using this, I get the following:

```
ts-standard output:
Unable to locate the project file. A project file (tsconfig.json or tsconfig.eslint.json) is required in order to use ts-standard.
```

my tsconfig.json file is not in the root of the project, but the whole ts project is in a subfolder, could that be the issue?

**Comment by sambauers** [comment]
Not having a `tsconfig.josn` in the root is probably the issue. You can create one there which references the one in the sub-directory. You should be able to name the config in your root directory either `tsconfig.json` or `tsconfig.eslint.json`.
